addSbtPlugin("com.47deg"         % "sbt-microsites" % "0.7.27")
//addSbtPlugin("org.tpolecat"      % "tut-plugin"     % "0.6.12")
addSbtPlugin("com.github.gseitz" % "sbt-release"    % "1.0.10")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"   % "2.4")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"        % "1.1.0")
